services:
  backend-v1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3001"
    env_file:
      - .env

  backend-v2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3001"
    env_file:
      - .env

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - ./ml-service/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "3000:80"

networks:
  default:
    name: iptv-network
    external: true
