events {}

http {
  client_max_body_size 100M;

  proxy_buffer_size 512k;
  proxy_buffers 8 512k;
  proxy_busy_buffers_size 512k;
  large_client_header_buffers 8 512k;

  upstream backend_pool {
    server backend-v1:3001 max_fails=3 fail_timeout=10s;
    server backend-v2:3001 max_fails=3 fail_timeout=10s;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend_pool;

      proxy_connect_timeout 60s;
      proxy_send_timeout 60s;
      proxy_read_timeout 60s;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_next_upstream error timeout http_502 http_503 http_504;
    }

    location /internal/ {
      proxy_pass http://backend_pool;
    }

    location /ml/ {
      proxy_pass http://ml-service:8080;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Prefix /ml;
      
      proxy_connect_timeout 60s;
      proxy_send_timeout 300s;
      proxy_read_timeout 300s;
      send_timeout 300s;
    }
    
    location /ml/docs {
      proxy_pass http://ml-service:8080/docs;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Prefix /ml;
      
      proxy_connect_timeout 60s;
      proxy_send_timeout 300s;
      proxy_read_timeout 300s;
      
      send_timeout 300s;
    }

    location /ml/openapi.json {
      proxy_pass http://ml-service:8080/openapi.json;

      proxy_connect_timeout 60s;
      proxy_send_timeout 300s;
      proxy_read_timeout 300s;
      
      send_timeout 300s;
    }

    location /health {
      proxy_pass http://backend_pool;
    }

    location = /jenkins {
      return 301 /jenkins/;
    }

    location /jenkins/ {
      proxy_pass http://jenkins:8080;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Prefix /jenkins;

      proxy_redirect off;

      send_timeout 90;
      proxy_read_timeout 90;
      proxy_connect_timeout 90;
    }

    location /grafana/ {
      proxy_set_header Host $host; # PENTING untuk mengatasi Origin Not Allowed
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme; # PENTING: memberi tahu Grafana ini HTTPS

      proxy_pass http://grafana:3000;
    }

    location /prometheus/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      
      # Pastikan ini menembak ke /prometheus/ karena kita pakai --web.external-url
      proxy_pass http://prometheus:9090/prometheus/;
    }

    location /cadvisor/ {
      proxy_pass http://cadvisor:8080/;
    }
  }
}