events {}

http {
  upstream backend_pool {
    server backend-v1:3001;
    server backend-v2:3001;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend_pool;
    }

    location /internal/ {
      proxy_pass http://backend_pool;
    }

    location /ml/ {
      proxy_pass http://ml-service:8080;
    }

    location /health {
      proxy_pass http://backend_pool;
    }
  }
}